name: Python CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: patient
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install Flask SQLAlchemy mysqlclient pytest pytest-flask pymysql Flask-SQLAlchemy flask-httpauth cryptography

      - name: Create MySQL user
        run: |
          docker exec ${{ job.services.mysql.id }} \
          mysql -u root -proot_password -e "CREATE USER 'username'@'%' IDENTIFIED BY 'password'; \
          GRANT ALL PRIVILEGES ON *.* TO 'username'@'%'; FLUSH PRIVILEGES;"

      - name: Create .env file
        run: |
          echo "export FLASK_APP=~/webapp.py" >> $GITHUB_ENV
          echo "export FLASK_ENV=development" >> $GITHUB_ENV
          echo "export SQLALCHEMY_DATABASE_URI='mysql+pymysql://username:password@localhost/patient'" >> $GITHUB_ENV
          echo "export HOSTNAME='0.0.0.0'" >> $GITHUB_ENV
          source $GITHUB_ENV

      - name: Wait for MySQL to be ready
        run: sleep 15s

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest
